# Generated by Django 3.1.7 on 2021-04-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210405_0413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['index'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
